version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 1
  versioning-strategy: widen
  ignore:
  - dependency-name: php-di/php-di
    versions:
    - 6.3.0
